//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyExcelApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentList
    {
        public int RollNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> Marks { get; set; }
        public string Result { get; set; }
    }
}
